app:
  name: "MyApp"
  version: "1.0.0"
  number: 10
  mqtt:
    broker: "tcp://127.0.0.1:1883"
    clientId: "client"
    username: "admin"
    password: "public"

list:
  - 10
  - 20

listlist:
  - [ "list.0.0", "list.0.1" ]
  - [ "list.1.0", "list.1.1" ]

structs:
  - name: "John"
    age: 20
    list:
      - true
      - false
  - name: "Doe"
    age: 30
    list:
      - true
      - false